input_dir: ${PROJECT_DIR}/SwiftGenTutorial
output_dir: ${PROJECT_DIR}/SwiftGenTutorial/SwiftGenConfig
xcassets:
  inputs:
    - Assets.xcassets
    - Colors.xcassets
  outputs:
    - templatePath: ${PROJECT_DIR}/SwiftGenTutorial/SwiftGenConfig/template.stencil
      params:
        publicAccess: true
      output: Assets.generated.swift
